version: '4'

services:
  cassandra:
    image: cassandra:4.1.0
    container_name: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=test
  init-cassandra:
    image: cassandra:4.1.0
    container_name: cassandra-init
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: [ "/init.sh" ]
    volumes:
      - ./cassandra-init-data.sh:/init.sh
#  product-maintainer:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - cassandra